title: Блог нашей команды
remote_theme: pages-themes/minimal # Опционально, можно оставить пустым
collections:
  students:
    output: true # Разрешает Jekyll создавать отдельные страницы для каждого файла в _students
